# ─────────────────────────────────────────────────────────────
#  AXIOM Auto-Start Setup
#  Run this ONCE as Administrator on any machine.
#  After running, AXIOM will start automatically at every login
#  with full admin rights — no UAC prompt needed again.
# ─────────────────────────────────────────────────────────────

param(
    [switch]$Remove   # Pass -Remove to unregister the task
)

# ── Paths ──────────────────────────────────────────────────────
$scriptDir  = Split-Path $MyInvocation.MyCommand.Path -Parent
$projectDir = Split-Path $scriptDir -Parent
$axiomDir   = Join-Path $projectDir "axiom"
$launchVbs  = Join-Path $scriptDir "launch-axiom.vbs"
$taskName   = "AXIOM Startup"

# ── Guard: must be admin ───────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host ""
    Write-Host "  ERROR: Run this script as Administrator." -ForegroundColor Red
    Write-Host "  Right-click PowerShell → 'Run as administrator', then re-run." -ForegroundColor Yellow
    Write-Host ""
    pause
    exit 1
}

# ── Remove mode ────────────────────────────────────────────────
if ($Remove) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "  AXIOM auto-start removed." -ForegroundColor Yellow
    exit 0
}

# ── Verify axiom directory exists ─────────────────────────────
if (-not (Test-Path $axiomDir)) {
    Write-Host ""
    Write-Host "  ERROR: axiom folder not found at: $axiomDir" -ForegroundColor Red
    Write-Host "  Make sure you're running this from inside the cloned repo." -ForegroundColor Yellow
    Write-Host ""
    pause
    exit 1
}

# ── Verify node_modules ───────────────────────────────────────
$electronBin = Join-Path $axiomDir "node_modules\.bin\electron.cmd"
if (-not (Test-Path $electronBin)) {
    Write-Host ""
    Write-Host "  ERROR: node_modules not found. Run 'npm install' inside the axiom folder first." -ForegroundColor Red
    Write-Host ""
    pause
    exit 1
}

# ── Generate the VBScript launcher (hides the console window) ─
$vbsContent = @"
' AXIOM silent launcher — generated by setup-autostart.ps1
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$axiomDir"
shell.Run "cmd /c ""npx electron . --hidden""", 0, False
"@

Set-Content -Path $launchVbs -Value $vbsContent -Encoding Default
Write-Host "  Launcher created: $launchVbs" -ForegroundColor Cyan

# ── Register the scheduled task ────────────────────────────────
$currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

$action  = New-ScheduledTaskAction `
    -Execute "wscript.exe" `
    -Argument "`"$launchVbs`"" `
    -WorkingDirectory $axiomDir

$trigger = New-ScheduledTaskTrigger -AtLogOn -User $currentUser

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -Priority 0   # 0 = highest priority - AXIOM launches before other startup apps

$principal = New-ScheduledTaskPrincipal `
    -UserId $currentUser `
    -LogonType Interactive `
    -RunLevel Highest    # ← this is what gives admin rights without UAC

# Remove existing task if present, then register fresh
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "Starts AXIOM voice assistant at login with administrator privileges." `
    | Out-Null

Write-Host ""
Write-Host "  ✓  AXIOM will now start automatically at every login." -ForegroundColor Green
Write-Host "  ✓  Runs as Administrator — no UAC popup." -ForegroundColor Green
Write-Host "  ✓  Task name: '$taskName'" -ForegroundColor Green
Write-Host ""
Write-Host "  To remove auto-start later, run:" -ForegroundColor Gray
Write-Host "    powershell -File setup-autostart.ps1 -Remove" -ForegroundColor Gray
Write-Host ""

# Offer to start AXIOM right now
$startNow = Read-Host "  Start AXIOM now? (y/n)"
if ($startNow -eq 'y' -or $startNow -eq 'Y') {
    Start-Process "wscript.exe" -ArgumentList "`"$launchVbs`""
    Write-Host "  AXIOM is starting..." -ForegroundColor Cyan
}
